/**
 * @package
 */
export const prefList = [
  {
    id: '1',
    name: '北海道',
    city: 'Sapporo',
    latitude: 43.03,
    longlatitude: 141.2,
  },
  {
    id: '2',
    name: '青森県',
    city: 'Aomori',
    latitude: 40.49,
    longlatitude: 140.44,
  },
  {
    id: '3',
    name: '岩手県',
    city: 'Morioka',
    latitude: 39.42,
    longlatitude: 141.09,
  },
  {
    id: '4',
    name: '宮城県',
    city: 'Sendai',
    latitude: 38.16,
    longlatitude: 140.52,
  },
  {
    id: '5',
    name: '秋田県',
    city: 'Akita',
    latitude: 39.43,
    longlatitude: 140.06,
  },
  {
    id: '6',
    name: '山形県',
    city: 'Yamagata',
    latitude: 38.14,
    longlatitude: 140.21,
  },
  {
    id: '7',
    name: '福島県',
    city: 'Fukushima',
    latitude: 37.45,
    longlatitude: 140.28,
  },
  {
    id: '8',
    name: '茨城県',
    city: 'Mito',
    latitude: 36.2,
    longlatitude: 140.26,
  },
  {
    id: '9',
    name: '栃木県',
    city: 'Utsunomiya',
    latitude: 36.33,
    longlatitude: 139.53,
  },
  {
    id: '10',
    name: '群馬県',
    city: 'Maebashi',
    latitude: 36.23,
    longlatitude: 139.53,
  },
  {
    id: '11',
    name: '埼玉県',
    city: 'Saitama',
    latitude: 35.51,
    longlatitude: 139.38,
  },
  {
    id: '12',
    name: '千葉県',
    city: 'Chiba',
    latitude: 35.36,
    longlatitude: 140.07,
  },
  {
    id: '13',
    name: '東京都',
    city: 'Tokyo',
    latitude: 35.41,
    longlatitude: 139.41,
  },
  {
    id: '14',
    name: '神奈川県',
    city: 'Yokohama',
    latitude: 35.26,
    longlatitude: 139.38,
  },
  {
    id: '15',
    name: '新潟県',
    city: 'Niigata',
    latitude: 37.54,
    longlatitude: 139.01,
  },
  {
    id: '16',
    name: '富山県',
    city: 'Toyama',
    latitude: 36.41,
    longlatitude: 137.12,
  },
  {
    id: '17',
    name: '石川県',
    city: 'Kanazawa',
    latitude: 36.35,
    longlatitude: 136.37,
  },
  {
    id: '18',
    name: '福井県',
    city: 'Fukui',
    latitude: 36.03,
    longlatitude: 136.13,
  },
  {
    id: '19',
    name: '山梨県',
    city: 'Kofu',
    latitude: 35.39,
    longlatitude: 138.34,
  },
  {
    id: '20',
    name: '長野県',
    city: 'Nagano',
    latitude: 36.39,
    longlatitude: 138.1,
  },
  {
    id: '21',
    name: '岐阜県',
    city: 'Gifu',
    latitude: 35.23,
    longlatitude: 136.43,
  },
  {
    id: '22',
    name: '静岡県',
    city: 'Shizuoka',
    latitude: 34.58,
    longlatitude: 138.22,
  },
  {
    id: '23',
    name: '愛知県',
    city: 'Nagoya',
    latitude: 35.1,
    longlatitude: 136.54,
  },
  {
    id: '24',
    name: '三重県',
    city: 'Tsu',
    latitude: 34.43,
    longlatitude: 136.3,
  },
  {
    id: '25',
    name: '滋賀県',
    city: 'Otsu',
    latitude: 35.0,
    longlatitude: 135.52,
  },
  {
    id: '26',
    name: '京都府',
    city: 'Kyoto',
    latitude: 35.01,
    longlatitude: 135.45,
  },
  {
    id: '27',
    name: '大阪府',
    city: 'Osaka',
    latitude: 34.41,
    longlatitude: 135.31,
  },
  {
    id: '28',
    name: '兵庫県',
    city: 'Kobe',
    latitude: 34.41,
    longlatitude: 135.1,
  },
  {
    id: '29',
    name: '奈良県',
    city: 'Nara',
    latitude: 34.41,
    longlatitude: 135.49,
  },
  {
    id: '30',
    name: '和歌山県',
    city: 'Wakayama',
    latitude: 34.13,
    longlatitude: 135.1,
  },
  {
    id: '31',
    name: '鳥取県',
    city: 'Tottori',
    latitude: 35.3,
    longlatitude: 134.14,
  },
  {
    id: '32',
    name: '島根県',
    city: 'Matsue',
    latitude: 35.28,
    longlatitude: 133.03,
  },
  {
    id: '33',
    name: '岡山県',
    city: 'Okayama',
    latitude: 34.39,
    longlatitude: 133.56,
  },
  {
    id: '34',
    name: '広島県',
    city: 'Hiroshima',
    latitude: 34.23,
    longlatitude: 132.27,
  },
  {
    id: '35',
    name: '山口県',
    city: 'Yamaguchi',
    latitude: 34.11,
    longlatitude: 131.28,
  },
  {
    id: '36',
    name: '徳島県',
    city: 'Tokushima',
    latitude: 34.03,
    longlatitude: 134.33,
  },
  {
    id: '37',
    name: '香川県',
    city: 'Takamatsu',
    latitude: 34.2,
    longlatitude: 134.02,
  },
  {
    id: '38',
    name: '愛媛県',
    city: 'Matsuyama',
    latitude: 33.5,
    longlatitude: 132.45,
  },
  {
    id: '39',
    name: '高知県',
    city: 'Kochi',
    latitude: 33.33,
    longlatitude: 133.31,
  },
  {
    id: '40',
    name: '福岡県',
    city: 'Fukuoka',
    latitude: 33.36,
    longlatitude: 130.25,
  },
  {
    id: '41',
    name: '佐賀県',
    city: 'Saga',
    latitude: 33.14,
    longlatitude: 130.17,
  },
  {
    id: '42',
    name: '長崎県',
    city: 'Nagasaki',
    latitude: 32.45,
    longlatitude: 129.52,
  },
  {
    id: '43',
    name: '熊本県',
    city: 'Kumamoto',
    latitude: 32.47,
    longlatitude: 130.44,
  },
  {
    id: '44',
    name: '大分県',
    city: 'Oita',
    latitude: 33.14,
    longlatitude: 131.36,
  },
  {
    id: '45',
    name: '宮崎県',
    city: 'Miyazaki',
    latitude: 31.54,
    longlatitude: 131.25,
  },
  {
    id: '46',
    name: '鹿児島県',
    city: 'Kagoshima',
    latitude: 31.33,
    longlatitude: 130.33,
  },
  {
    id: '47',
    name: '沖縄県',
    city: 'Naha',
    latitude: 26.12,
    longlatitude: 127.4,
  },
] as const
