/**
 * @package
 */
export const prefList = [
  { id: 1, name: '北海道', city: 'Sapporo' },
  { id: 2, name: '青森県', city: 'Aomori' },
  { id: 3, name: '岩手県', city: 'Morioka' },
  { id: 4, name: '宮城県', city: 'Sendai' },
  { id: 5, name: '秋田県', city: 'Akita' },
  { id: 6, name: '山形県', city: 'Yamagata' },
  { id: 7, name: '福島県', city: 'Fukushima' },
  { id: 8, name: '茨城県', city: 'Mito' },
  { id: 9, name: '栃木県', city: 'Utsunomiya' },
  { id: 10, name: '群馬県', city: 'Maebashi' },
  { id: 11, name: '埼玉県', city: 'Saitama' },
  { id: 12, name: '千葉県', city: 'Chiba' },
  { id: 13, name: '東京都', city: 'Tokyo' },
  { id: 14, name: '神奈川県', city: 'Yokohama' },
  { id: 15, name: '新潟県', city: 'Niigata' },
  { id: 16, name: '富山県', city: 'Toyama' },
  { id: 17, name: '石川県', city: 'Kanazawa' },
  { id: 18, name: '福井県', city: 'Fukui' },
  { id: 19, name: '山梨県', city: 'Kofu' },
  { id: 20, name: '長野県', city: 'Nagano' },
  { id: 21, name: '岐阜県', city: 'Gifu' },
  { id: 22, name: '静岡県', city: 'Shizuoka' },
  { id: 23, name: '愛知県', city: 'Nagoya' },
  { id: 24, name: '三重県', city: 'Tsu' },
  { id: 25, name: '滋賀県', city: 'Otsu' },
  { id: 26, name: '京都府', city: 'Kyoto' },
  { id: 27, name: '大阪府', city: 'Osaka' },
  { id: 28, name: '兵庫県', city: 'Kobe' },
  { id: 29, name: '奈良県', city: 'Nara' },
  { id: 30, name: '和歌山県', city: 'Wakayama' },
  { id: 31, name: '鳥取県', city: 'Tottori' },
  { id: 32, name: '島根県', city: 'Matsue' },
  { id: 33, name: '岡山県', city: 'Okayama' },
  { id: 34, name: '広島県', city: 'Hiroshima' },
  { id: 35, name: '山口県', city: 'Yamaguchi' },
  { id: 36, name: '徳島県', city: 'Tokushima' },
  { id: 37, name: '香川県', city: 'Takamatsu' },
  { id: 38, name: '愛媛県', city: 'Matsuyama' },
  { id: 39, name: '高知県', city: 'Kochi' },
  { id: 40, name: '福岡県', city: 'Fukuoka' },
  { id: 41, name: '佐賀県', city: 'Saga' },
  { id: 42, name: '長崎県', city: 'Nagasaki' },
  { id: 43, name: '熊本県', city: 'Kumamoto' },
  { id: 44, name: '大分県', city: 'Oita' },
  { id: 45, name: '宮崎県', city: 'Miyazaki' },
  { id: 46, name: '鹿児島県', city: 'Kagoshima' },
  { id: 47, name: '沖縄県', city: 'Naha' },
] as const
